[package]
name = "polygon_canvas"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.25.2"
ndarray = "0.15.6"
num-traits = "0.2.19"
palette = "0.7.6"
